// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.sourcesink.consumer;

public interface ProducerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:consumergrpc.ProducerRequest)
    com.google.protobuf.MessageOrBuilder {
}
