// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.source.queue;

public final class queue {
  private queue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_ResponseFromQueueSource_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_ResponseFromQueueSource_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_queue_RequestFromSink_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_queue_RequestFromSink_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ProducerConsumerContract.proto\022\005queue\"" +
      "\'\n\027ResponseFromQueueSource\022\014\n\004file\030\001 \003(\014" +
      "\"\021\n\017RequestFromSink2\\\n\023GetMessageFromQue" +
      "ue\022E\n\007getItem\022\026.queue.RequestFromSink\032\036." +
      "queue.ResponseFromQueueSource\"\0000\001B\035\n\020com" +
      ".source.queueB\005queueH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_queue_ResponseFromQueueSource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_queue_ResponseFromQueueSource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_ResponseFromQueueSource_descriptor,
        new java.lang.String[] { "File", });
    internal_static_queue_RequestFromSink_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_queue_RequestFromSink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_queue_RequestFromSink_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
