// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.source.queue;

public interface RequestFromSinkOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.RequestFromSink)
    com.google.protobuf.MessageOrBuilder {
}
