// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.source.queue;

public interface ResponseFromQueueSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.ResponseFromQueueSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();
}
