// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.sink.queue;

public interface ResponseFromQueueSourceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:queue.ResponseFromQueueSource)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated bytes file = 1;</code>
   */
  java.util.List<com.google.protobuf.ByteString> getFileList();
  /**
   * <code>repeated bytes file = 1;</code>
   */
  int getFileCount();
  /**
   * <code>repeated bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile(int index);
}
