// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.sourcesink.producer;

public interface ProducerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producergrpc.ProducerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes file = 1;</code>
   */
  com.google.protobuf.ByteString getFile();
}
