// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProducerConsumerContract.proto

package com.sourcesink.producer;

public interface ProducerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:producergrpc.ProducerRequest)
    com.google.protobuf.MessageOrBuilder {
}
